//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="BombochaGJEsSoap", Namespace="http://tempuri.org/")]
public partial class BombochaGJEs : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
    
    private System.Threading.SendOrPostCallback SelectLstCatalogoTamanioJSONOperationCompleted;
    
    private System.Threading.SendOrPostCallback SelectLstCatalogoEscenariosJSONOperationCompleted;
    
    private System.Threading.SendOrPostCallback SelectLstCatalogoCanicaJSONOperationCompleted;
    
    private System.Threading.SendOrPostCallback SelectLstCatalogoTamanioOperationCompleted;
    
    private System.Threading.SendOrPostCallback SelectLstCatalogoEscenariosOperationCompleted;
    
    private System.Threading.SendOrPostCallback SelectLstCatalogoCanicaOperationCompleted;
    
    private System.Threading.SendOrPostCallback InsertUpdateUsuariosJSONOperationCompleted;
    
    private System.Threading.SendOrPostCallback InsertAmigoJSONOperationCompleted;
    
    private System.Threading.SendOrPostCallback InsertCanicaJSONOperationCompleted;
    
    private System.Threading.SendOrPostCallback InsertJuegoJSONOperationCompleted;
    
    private System.Threading.SendOrPostCallback InsertUpdateUsuariosOperationCompleted;
    
    private System.Threading.SendOrPostCallback InsertAmigoOperationCompleted;
    
    private System.Threading.SendOrPostCallback InsertCanicaOperationCompleted;
    
    private System.Threading.SendOrPostCallback InsertJuegoOperationCompleted;
    
    private System.Threading.SendOrPostCallback SelectJuegoXIDJuegoJSONOperationCompleted;
    
    private System.Threading.SendOrPostCallback SelectLstCanicasXIDJuegoJSONOperationCompleted;
    
    private System.Threading.SendOrPostCallback SelectLstJuegosXsAliasJSONOperationCompleted;
    
    private System.Threading.SendOrPostCallback UsuarioLoginJSONOperationCompleted;
    
    private System.Threading.SendOrPostCallback SelectJuegoXIDJuegoOperationCompleted;
    
    private System.Threading.SendOrPostCallback SelectLstCanicasXIDJuegoOperationCompleted;
    
    private System.Threading.SendOrPostCallback SelectLstJuegosXsAliasOperationCompleted;
    
    private System.Threading.SendOrPostCallback UsuarioLoginOperationCompleted;
    
    private System.Threading.SendOrPostCallback DeleteAmigoJSONOperationCompleted;
    
    private System.Threading.SendOrPostCallback DeleteJuegoJSONOperationCompleted;
    
    private System.Threading.SendOrPostCallback DeleteAmigoOperationCompleted;
    
    private System.Threading.SendOrPostCallback DeleteJuegoOperationCompleted;
    
    /// <remarks/>
    public BombochaGJEs() {
        this.Url = "http://frailetoc.com/GAMES/BombochaGJEs/WS/WS/BombochaGJEs.asmx";
    }
    
    /// <remarks/>
    public event HelloWorldCompletedEventHandler HelloWorldCompleted;
    
    /// <remarks/>
    public event SelectLstCatalogoTamanioJSONCompletedEventHandler SelectLstCatalogoTamanioJSONCompleted;
    
    /// <remarks/>
    public event SelectLstCatalogoEscenariosJSONCompletedEventHandler SelectLstCatalogoEscenariosJSONCompleted;
    
    /// <remarks/>
    public event SelectLstCatalogoCanicaJSONCompletedEventHandler SelectLstCatalogoCanicaJSONCompleted;
    
    /// <remarks/>
    public event SelectLstCatalogoTamanioCompletedEventHandler SelectLstCatalogoTamanioCompleted;
    
    /// <remarks/>
    public event SelectLstCatalogoEscenariosCompletedEventHandler SelectLstCatalogoEscenariosCompleted;
    
    /// <remarks/>
    public event SelectLstCatalogoCanicaCompletedEventHandler SelectLstCatalogoCanicaCompleted;
    
    /// <remarks/>
    public event InsertUpdateUsuariosJSONCompletedEventHandler InsertUpdateUsuariosJSONCompleted;
    
    /// <remarks/>
    public event InsertAmigoJSONCompletedEventHandler InsertAmigoJSONCompleted;
    
    /// <remarks/>
    public event InsertCanicaJSONCompletedEventHandler InsertCanicaJSONCompleted;
    
    /// <remarks/>
    public event InsertJuegoJSONCompletedEventHandler InsertJuegoJSONCompleted;
    
    /// <remarks/>
    public event InsertUpdateUsuariosCompletedEventHandler InsertUpdateUsuariosCompleted;
    
    /// <remarks/>
    public event InsertAmigoCompletedEventHandler InsertAmigoCompleted;
    
    /// <remarks/>
    public event InsertCanicaCompletedEventHandler InsertCanicaCompleted;
    
    /// <remarks/>
    public event InsertJuegoCompletedEventHandler InsertJuegoCompleted;
    
    /// <remarks/>
    public event SelectJuegoXIDJuegoJSONCompletedEventHandler SelectJuegoXIDJuegoJSONCompleted;
    
    /// <remarks/>
    public event SelectLstCanicasXIDJuegoJSONCompletedEventHandler SelectLstCanicasXIDJuegoJSONCompleted;
    
    /// <remarks/>
    public event SelectLstJuegosXsAliasJSONCompletedEventHandler SelectLstJuegosXsAliasJSONCompleted;
    
    /// <remarks/>
    public event UsuarioLoginJSONCompletedEventHandler UsuarioLoginJSONCompleted;
    
    /// <remarks/>
    public event SelectJuegoXIDJuegoCompletedEventHandler SelectJuegoXIDJuegoCompleted;
    
    /// <remarks/>
    public event SelectLstCanicasXIDJuegoCompletedEventHandler SelectLstCanicasXIDJuegoCompleted;
    
    /// <remarks/>
    public event SelectLstJuegosXsAliasCompletedEventHandler SelectLstJuegosXsAliasCompleted;
    
    /// <remarks/>
    public event UsuarioLoginCompletedEventHandler UsuarioLoginCompleted;
    
    /// <remarks/>
    public event DeleteAmigoJSONCompletedEventHandler DeleteAmigoJSONCompleted;
    
    /// <remarks/>
    public event DeleteJuegoJSONCompletedEventHandler DeleteJuegoJSONCompleted;
    
    /// <remarks/>
    public event DeleteAmigoCompletedEventHandler DeleteAmigoCompleted;
    
    /// <remarks/>
    public event DeleteJuegoCompletedEventHandler DeleteJuegoCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string HelloWorld() {
        object[] results = this.Invoke("HelloWorld", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndHelloWorld(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void HelloWorldAsync() {
        this.HelloWorldAsync(null);
    }
    
    /// <remarks/>
    public void HelloWorldAsync(object userState) {
        if ((this.HelloWorldOperationCompleted == null)) {
            this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
        }
        this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
    }
    
    private void OnHelloWorldOperationCompleted(object arg) {
        if ((this.HelloWorldCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectLstCatalogoTamanioJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void SelectLstCatalogoTamanioJSON() {
        this.Invoke("SelectLstCatalogoTamanioJSON", new object[0]);
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSelectLstCatalogoTamanioJSON(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SelectLstCatalogoTamanioJSON", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public void EndSelectLstCatalogoTamanioJSON(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void SelectLstCatalogoTamanioJSONAsync() {
        this.SelectLstCatalogoTamanioJSONAsync(null);
    }
    
    /// <remarks/>
    public void SelectLstCatalogoTamanioJSONAsync(object userState) {
        if ((this.SelectLstCatalogoTamanioJSONOperationCompleted == null)) {
            this.SelectLstCatalogoTamanioJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectLstCatalogoTamanioJSONOperationCompleted);
        }
        this.InvokeAsync("SelectLstCatalogoTamanioJSON", new object[0], this.SelectLstCatalogoTamanioJSONOperationCompleted, userState);
    }
    
    private void OnSelectLstCatalogoTamanioJSONOperationCompleted(object arg) {
        if ((this.SelectLstCatalogoTamanioJSONCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SelectLstCatalogoTamanioJSONCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectLstCatalogoEscenariosJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void SelectLstCatalogoEscenariosJSON() {
        this.Invoke("SelectLstCatalogoEscenariosJSON", new object[0]);
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSelectLstCatalogoEscenariosJSON(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SelectLstCatalogoEscenariosJSON", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public void EndSelectLstCatalogoEscenariosJSON(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void SelectLstCatalogoEscenariosJSONAsync() {
        this.SelectLstCatalogoEscenariosJSONAsync(null);
    }
    
    /// <remarks/>
    public void SelectLstCatalogoEscenariosJSONAsync(object userState) {
        if ((this.SelectLstCatalogoEscenariosJSONOperationCompleted == null)) {
            this.SelectLstCatalogoEscenariosJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectLstCatalogoEscenariosJSONOperationCompleted);
        }
        this.InvokeAsync("SelectLstCatalogoEscenariosJSON", new object[0], this.SelectLstCatalogoEscenariosJSONOperationCompleted, userState);
    }
    
    private void OnSelectLstCatalogoEscenariosJSONOperationCompleted(object arg) {
        if ((this.SelectLstCatalogoEscenariosJSONCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SelectLstCatalogoEscenariosJSONCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectLstCatalogoCanicaJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void SelectLstCatalogoCanicaJSON() {
        this.Invoke("SelectLstCatalogoCanicaJSON", new object[0]);
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSelectLstCatalogoCanicaJSON(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SelectLstCatalogoCanicaJSON", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public void EndSelectLstCatalogoCanicaJSON(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void SelectLstCatalogoCanicaJSONAsync() {
        this.SelectLstCatalogoCanicaJSONAsync(null);
    }
    
    /// <remarks/>
    public void SelectLstCatalogoCanicaJSONAsync(object userState) {
        if ((this.SelectLstCatalogoCanicaJSONOperationCompleted == null)) {
            this.SelectLstCatalogoCanicaJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectLstCatalogoCanicaJSONOperationCompleted);
        }
        this.InvokeAsync("SelectLstCatalogoCanicaJSON", new object[0], this.SelectLstCatalogoCanicaJSONOperationCompleted, userState);
    }
    
    private void OnSelectLstCatalogoCanicaJSONOperationCompleted(object arg) {
        if ((this.SelectLstCatalogoCanicaJSONCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SelectLstCatalogoCanicaJSONCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectLstCatalogoTamanio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public SelectLstCatalogoTamanioResult[] SelectLstCatalogoTamanio() {
        object[] results = this.Invoke("SelectLstCatalogoTamanio", new object[0]);
        return ((SelectLstCatalogoTamanioResult[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSelectLstCatalogoTamanio(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SelectLstCatalogoTamanio", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public SelectLstCatalogoTamanioResult[] EndSelectLstCatalogoTamanio(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((SelectLstCatalogoTamanioResult[])(results[0]));
    }
    
    /// <remarks/>
    public void SelectLstCatalogoTamanioAsync() {
        this.SelectLstCatalogoTamanioAsync(null);
    }
    
    /// <remarks/>
    public void SelectLstCatalogoTamanioAsync(object userState) {
        if ((this.SelectLstCatalogoTamanioOperationCompleted == null)) {
            this.SelectLstCatalogoTamanioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectLstCatalogoTamanioOperationCompleted);
        }
        this.InvokeAsync("SelectLstCatalogoTamanio", new object[0], this.SelectLstCatalogoTamanioOperationCompleted, userState);
    }
    
    private void OnSelectLstCatalogoTamanioOperationCompleted(object arg) {
        if ((this.SelectLstCatalogoTamanioCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SelectLstCatalogoTamanioCompleted(this, new SelectLstCatalogoTamanioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectLstCatalogoEscenarios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public SelectLstCatalogoEscenariosResult[] SelectLstCatalogoEscenarios() {
        object[] results = this.Invoke("SelectLstCatalogoEscenarios", new object[0]);
        return ((SelectLstCatalogoEscenariosResult[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSelectLstCatalogoEscenarios(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SelectLstCatalogoEscenarios", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public SelectLstCatalogoEscenariosResult[] EndSelectLstCatalogoEscenarios(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((SelectLstCatalogoEscenariosResult[])(results[0]));
    }
    
    /// <remarks/>
    public void SelectLstCatalogoEscenariosAsync() {
        this.SelectLstCatalogoEscenariosAsync(null);
    }
    
    /// <remarks/>
    public void SelectLstCatalogoEscenariosAsync(object userState) {
        if ((this.SelectLstCatalogoEscenariosOperationCompleted == null)) {
            this.SelectLstCatalogoEscenariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectLstCatalogoEscenariosOperationCompleted);
        }
        this.InvokeAsync("SelectLstCatalogoEscenarios", new object[0], this.SelectLstCatalogoEscenariosOperationCompleted, userState);
    }
    
    private void OnSelectLstCatalogoEscenariosOperationCompleted(object arg) {
        if ((this.SelectLstCatalogoEscenariosCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SelectLstCatalogoEscenariosCompleted(this, new SelectLstCatalogoEscenariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectLstCatalogoCanica", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public SelectLstCatalogoCanicaResult[] SelectLstCatalogoCanica() {
        object[] results = this.Invoke("SelectLstCatalogoCanica", new object[0]);
        return ((SelectLstCatalogoCanicaResult[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSelectLstCatalogoCanica(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SelectLstCatalogoCanica", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public SelectLstCatalogoCanicaResult[] EndSelectLstCatalogoCanica(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((SelectLstCatalogoCanicaResult[])(results[0]));
    }
    
    /// <remarks/>
    public void SelectLstCatalogoCanicaAsync() {
        this.SelectLstCatalogoCanicaAsync(null);
    }
    
    /// <remarks/>
    public void SelectLstCatalogoCanicaAsync(object userState) {
        if ((this.SelectLstCatalogoCanicaOperationCompleted == null)) {
            this.SelectLstCatalogoCanicaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectLstCatalogoCanicaOperationCompleted);
        }
        this.InvokeAsync("SelectLstCatalogoCanica", new object[0], this.SelectLstCatalogoCanicaOperationCompleted, userState);
    }
    
    private void OnSelectLstCatalogoCanicaOperationCompleted(object arg) {
        if ((this.SelectLstCatalogoCanicaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SelectLstCatalogoCanicaCompleted(this, new SelectLstCatalogoCanicaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertUpdateUsuariosJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void InsertUpdateUsuariosJSON(string eMail, string sAlias, string sPass, string sConfirm) {
        this.Invoke("InsertUpdateUsuariosJSON", new object[] {
                    eMail,
                    sAlias,
                    sPass,
                    sConfirm});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginInsertUpdateUsuariosJSON(string eMail, string sAlias, string sPass, string sConfirm, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("InsertUpdateUsuariosJSON", new object[] {
                    eMail,
                    sAlias,
                    sPass,
                    sConfirm}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndInsertUpdateUsuariosJSON(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void InsertUpdateUsuariosJSONAsync(string eMail, string sAlias, string sPass, string sConfirm) {
        this.InsertUpdateUsuariosJSONAsync(eMail, sAlias, sPass, sConfirm, null);
    }
    
    /// <remarks/>
    public void InsertUpdateUsuariosJSONAsync(string eMail, string sAlias, string sPass, string sConfirm, object userState) {
        if ((this.InsertUpdateUsuariosJSONOperationCompleted == null)) {
            this.InsertUpdateUsuariosJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertUpdateUsuariosJSONOperationCompleted);
        }
        this.InvokeAsync("InsertUpdateUsuariosJSON", new object[] {
                    eMail,
                    sAlias,
                    sPass,
                    sConfirm}, this.InsertUpdateUsuariosJSONOperationCompleted, userState);
    }
    
    private void OnInsertUpdateUsuariosJSONOperationCompleted(object arg) {
        if ((this.InsertUpdateUsuariosJSONCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.InsertUpdateUsuariosJSONCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertAmigoJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void InsertAmigoJSON(int iDUsuario, int iDUsuarioAmigo) {
        this.Invoke("InsertAmigoJSON", new object[] {
                    iDUsuario,
                    iDUsuarioAmigo});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginInsertAmigoJSON(int iDUsuario, int iDUsuarioAmigo, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("InsertAmigoJSON", new object[] {
                    iDUsuario,
                    iDUsuarioAmigo}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndInsertAmigoJSON(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void InsertAmigoJSONAsync(int iDUsuario, int iDUsuarioAmigo) {
        this.InsertAmigoJSONAsync(iDUsuario, iDUsuarioAmigo, null);
    }
    
    /// <remarks/>
    public void InsertAmigoJSONAsync(int iDUsuario, int iDUsuarioAmigo, object userState) {
        if ((this.InsertAmigoJSONOperationCompleted == null)) {
            this.InsertAmigoJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertAmigoJSONOperationCompleted);
        }
        this.InvokeAsync("InsertAmigoJSON", new object[] {
                    iDUsuario,
                    iDUsuarioAmigo}, this.InsertAmigoJSONOperationCompleted, userState);
    }
    
    private void OnInsertAmigoJSONOperationCompleted(object arg) {
        if ((this.InsertAmigoJSONCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.InsertAmigoJSONCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertCanicaJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void InsertCanicaJSON(int iDUsuario, int iDJuego, int iDCatalogoCanica, double fX, double fY, double fZ) {
        this.Invoke("InsertCanicaJSON", new object[] {
                    iDUsuario,
                    iDJuego,
                    iDCatalogoCanica,
                    fX,
                    fY,
                    fZ});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginInsertCanicaJSON(int iDUsuario, int iDJuego, int iDCatalogoCanica, double fX, double fY, double fZ, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("InsertCanicaJSON", new object[] {
                    iDUsuario,
                    iDJuego,
                    iDCatalogoCanica,
                    fX,
                    fY,
                    fZ}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndInsertCanicaJSON(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void InsertCanicaJSONAsync(int iDUsuario, int iDJuego, int iDCatalogoCanica, double fX, double fY, double fZ) {
        this.InsertCanicaJSONAsync(iDUsuario, iDJuego, iDCatalogoCanica, fX, fY, fZ, null);
    }
    
    /// <remarks/>
    public void InsertCanicaJSONAsync(int iDUsuario, int iDJuego, int iDCatalogoCanica, double fX, double fY, double fZ, object userState) {
        if ((this.InsertCanicaJSONOperationCompleted == null)) {
            this.InsertCanicaJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertCanicaJSONOperationCompleted);
        }
        this.InvokeAsync("InsertCanicaJSON", new object[] {
                    iDUsuario,
                    iDJuego,
                    iDCatalogoCanica,
                    fX,
                    fY,
                    fZ}, this.InsertCanicaJSONOperationCompleted, userState);
    }
    
    private void OnInsertCanicaJSONOperationCompleted(object arg) {
        if ((this.InsertCanicaJSONCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.InsertCanicaJSONCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertJuegoJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void InsertJuegoJSON(int iDUsuario, int iDCatalogoEscenario, string sNombre) {
        this.Invoke("InsertJuegoJSON", new object[] {
                    iDUsuario,
                    iDCatalogoEscenario,
                    sNombre});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginInsertJuegoJSON(int iDUsuario, int iDCatalogoEscenario, string sNombre, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("InsertJuegoJSON", new object[] {
                    iDUsuario,
                    iDCatalogoEscenario,
                    sNombre}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndInsertJuegoJSON(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void InsertJuegoJSONAsync(int iDUsuario, int iDCatalogoEscenario, string sNombre) {
        this.InsertJuegoJSONAsync(iDUsuario, iDCatalogoEscenario, sNombre, null);
    }
    
    /// <remarks/>
    public void InsertJuegoJSONAsync(int iDUsuario, int iDCatalogoEscenario, string sNombre, object userState) {
        if ((this.InsertJuegoJSONOperationCompleted == null)) {
            this.InsertJuegoJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertJuegoJSONOperationCompleted);
        }
        this.InvokeAsync("InsertJuegoJSON", new object[] {
                    iDUsuario,
                    iDCatalogoEscenario,
                    sNombre}, this.InsertJuegoJSONOperationCompleted, userState);
    }
    
    private void OnInsertJuegoJSONOperationCompleted(object arg) {
        if ((this.InsertJuegoJSONCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.InsertJuegoJSONCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertUpdateUsuarios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public InsertUpdateUsuariosResult[] InsertUpdateUsuarios(string eMail, string sAlias, string sPass, string sConfirm) {
        object[] results = this.Invoke("InsertUpdateUsuarios", new object[] {
                    eMail,
                    sAlias,
                    sPass,
                    sConfirm});
        return ((InsertUpdateUsuariosResult[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginInsertUpdateUsuarios(string eMail, string sAlias, string sPass, string sConfirm, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("InsertUpdateUsuarios", new object[] {
                    eMail,
                    sAlias,
                    sPass,
                    sConfirm}, callback, asyncState);
    }
    
    /// <remarks/>
    public InsertUpdateUsuariosResult[] EndInsertUpdateUsuarios(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((InsertUpdateUsuariosResult[])(results[0]));
    }
    
    /// <remarks/>
    public void InsertUpdateUsuariosAsync(string eMail, string sAlias, string sPass, string sConfirm) {
        this.InsertUpdateUsuariosAsync(eMail, sAlias, sPass, sConfirm, null);
    }
    
    /// <remarks/>
    public void InsertUpdateUsuariosAsync(string eMail, string sAlias, string sPass, string sConfirm, object userState) {
        if ((this.InsertUpdateUsuariosOperationCompleted == null)) {
            this.InsertUpdateUsuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertUpdateUsuariosOperationCompleted);
        }
        this.InvokeAsync("InsertUpdateUsuarios", new object[] {
                    eMail,
                    sAlias,
                    sPass,
                    sConfirm}, this.InsertUpdateUsuariosOperationCompleted, userState);
    }
    
    private void OnInsertUpdateUsuariosOperationCompleted(object arg) {
        if ((this.InsertUpdateUsuariosCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.InsertUpdateUsuariosCompleted(this, new InsertUpdateUsuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertAmigo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string InsertAmigo(int iDUsuario, int iDUsuarioAmigo) {
        object[] results = this.Invoke("InsertAmigo", new object[] {
                    iDUsuario,
                    iDUsuarioAmigo});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginInsertAmigo(int iDUsuario, int iDUsuarioAmigo, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("InsertAmigo", new object[] {
                    iDUsuario,
                    iDUsuarioAmigo}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndInsertAmigo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void InsertAmigoAsync(int iDUsuario, int iDUsuarioAmigo) {
        this.InsertAmigoAsync(iDUsuario, iDUsuarioAmigo, null);
    }
    
    /// <remarks/>
    public void InsertAmigoAsync(int iDUsuario, int iDUsuarioAmigo, object userState) {
        if ((this.InsertAmigoOperationCompleted == null)) {
            this.InsertAmigoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertAmigoOperationCompleted);
        }
        this.InvokeAsync("InsertAmigo", new object[] {
                    iDUsuario,
                    iDUsuarioAmigo}, this.InsertAmigoOperationCompleted, userState);
    }
    
    private void OnInsertAmigoOperationCompleted(object arg) {
        if ((this.InsertAmigoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.InsertAmigoCompleted(this, new InsertAmigoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertCanica", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string InsertCanica(int iDUsuario, int iDJuego, int iDCatalogoCanica, double fX, double fY, double fZ) {
        object[] results = this.Invoke("InsertCanica", new object[] {
                    iDUsuario,
                    iDJuego,
                    iDCatalogoCanica,
                    fX,
                    fY,
                    fZ});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginInsertCanica(int iDUsuario, int iDJuego, int iDCatalogoCanica, double fX, double fY, double fZ, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("InsertCanica", new object[] {
                    iDUsuario,
                    iDJuego,
                    iDCatalogoCanica,
                    fX,
                    fY,
                    fZ}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndInsertCanica(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void InsertCanicaAsync(int iDUsuario, int iDJuego, int iDCatalogoCanica, double fX, double fY, double fZ) {
        this.InsertCanicaAsync(iDUsuario, iDJuego, iDCatalogoCanica, fX, fY, fZ, null);
    }
    
    /// <remarks/>
    public void InsertCanicaAsync(int iDUsuario, int iDJuego, int iDCatalogoCanica, double fX, double fY, double fZ, object userState) {
        if ((this.InsertCanicaOperationCompleted == null)) {
            this.InsertCanicaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertCanicaOperationCompleted);
        }
        this.InvokeAsync("InsertCanica", new object[] {
                    iDUsuario,
                    iDJuego,
                    iDCatalogoCanica,
                    fX,
                    fY,
                    fZ}, this.InsertCanicaOperationCompleted, userState);
    }
    
    private void OnInsertCanicaOperationCompleted(object arg) {
        if ((this.InsertCanicaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.InsertCanicaCompleted(this, new InsertCanicaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertJuego", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public InsertJuegoResult[] InsertJuego(int iDUsuario, int iDCatalogoEscenario, string sNombre) {
        object[] results = this.Invoke("InsertJuego", new object[] {
                    iDUsuario,
                    iDCatalogoEscenario,
                    sNombre});
        return ((InsertJuegoResult[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginInsertJuego(int iDUsuario, int iDCatalogoEscenario, string sNombre, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("InsertJuego", new object[] {
                    iDUsuario,
                    iDCatalogoEscenario,
                    sNombre}, callback, asyncState);
    }
    
    /// <remarks/>
    public InsertJuegoResult[] EndInsertJuego(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((InsertJuegoResult[])(results[0]));
    }
    
    /// <remarks/>
    public void InsertJuegoAsync(int iDUsuario, int iDCatalogoEscenario, string sNombre) {
        this.InsertJuegoAsync(iDUsuario, iDCatalogoEscenario, sNombre, null);
    }
    
    /// <remarks/>
    public void InsertJuegoAsync(int iDUsuario, int iDCatalogoEscenario, string sNombre, object userState) {
        if ((this.InsertJuegoOperationCompleted == null)) {
            this.InsertJuegoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertJuegoOperationCompleted);
        }
        this.InvokeAsync("InsertJuego", new object[] {
                    iDUsuario,
                    iDCatalogoEscenario,
                    sNombre}, this.InsertJuegoOperationCompleted, userState);
    }
    
    private void OnInsertJuegoOperationCompleted(object arg) {
        if ((this.InsertJuegoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.InsertJuegoCompleted(this, new InsertJuegoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectJuegoXIDJuegoJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void SelectJuegoXIDJuegoJSON(int iDJuego) {
        this.Invoke("SelectJuegoXIDJuegoJSON", new object[] {
                    iDJuego});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSelectJuegoXIDJuegoJSON(int iDJuego, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SelectJuegoXIDJuegoJSON", new object[] {
                    iDJuego}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndSelectJuegoXIDJuegoJSON(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void SelectJuegoXIDJuegoJSONAsync(int iDJuego) {
        this.SelectJuegoXIDJuegoJSONAsync(iDJuego, null);
    }
    
    /// <remarks/>
    public void SelectJuegoXIDJuegoJSONAsync(int iDJuego, object userState) {
        if ((this.SelectJuegoXIDJuegoJSONOperationCompleted == null)) {
            this.SelectJuegoXIDJuegoJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectJuegoXIDJuegoJSONOperationCompleted);
        }
        this.InvokeAsync("SelectJuegoXIDJuegoJSON", new object[] {
                    iDJuego}, this.SelectJuegoXIDJuegoJSONOperationCompleted, userState);
    }
    
    private void OnSelectJuegoXIDJuegoJSONOperationCompleted(object arg) {
        if ((this.SelectJuegoXIDJuegoJSONCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SelectJuegoXIDJuegoJSONCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectLstCanicasXIDJuegoJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void SelectLstCanicasXIDJuegoJSON(int iDJuego) {
        this.Invoke("SelectLstCanicasXIDJuegoJSON", new object[] {
                    iDJuego});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSelectLstCanicasXIDJuegoJSON(int iDJuego, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SelectLstCanicasXIDJuegoJSON", new object[] {
                    iDJuego}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndSelectLstCanicasXIDJuegoJSON(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void SelectLstCanicasXIDJuegoJSONAsync(int iDJuego) {
        this.SelectLstCanicasXIDJuegoJSONAsync(iDJuego, null);
    }
    
    /// <remarks/>
    public void SelectLstCanicasXIDJuegoJSONAsync(int iDJuego, object userState) {
        if ((this.SelectLstCanicasXIDJuegoJSONOperationCompleted == null)) {
            this.SelectLstCanicasXIDJuegoJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectLstCanicasXIDJuegoJSONOperationCompleted);
        }
        this.InvokeAsync("SelectLstCanicasXIDJuegoJSON", new object[] {
                    iDJuego}, this.SelectLstCanicasXIDJuegoJSONOperationCompleted, userState);
    }
    
    private void OnSelectLstCanicasXIDJuegoJSONOperationCompleted(object arg) {
        if ((this.SelectLstCanicasXIDJuegoJSONCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SelectLstCanicasXIDJuegoJSONCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectLstJuegosXsAliasJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void SelectLstJuegosXsAliasJSON(string sAlias) {
        this.Invoke("SelectLstJuegosXsAliasJSON", new object[] {
                    sAlias});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSelectLstJuegosXsAliasJSON(string sAlias, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SelectLstJuegosXsAliasJSON", new object[] {
                    sAlias}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndSelectLstJuegosXsAliasJSON(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void SelectLstJuegosXsAliasJSONAsync(string sAlias) {
        this.SelectLstJuegosXsAliasJSONAsync(sAlias, null);
    }
    
    /// <remarks/>
    public void SelectLstJuegosXsAliasJSONAsync(string sAlias, object userState) {
        if ((this.SelectLstJuegosXsAliasJSONOperationCompleted == null)) {
            this.SelectLstJuegosXsAliasJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectLstJuegosXsAliasJSONOperationCompleted);
        }
        this.InvokeAsync("SelectLstJuegosXsAliasJSON", new object[] {
                    sAlias}, this.SelectLstJuegosXsAliasJSONOperationCompleted, userState);
    }
    
    private void OnSelectLstJuegosXsAliasJSONOperationCompleted(object arg) {
        if ((this.SelectLstJuegosXsAliasJSONCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SelectLstJuegosXsAliasJSONCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UsuarioLoginJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void UsuarioLoginJSON(string eMail, string sPass) {
        this.Invoke("UsuarioLoginJSON", new object[] {
                    eMail,
                    sPass});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUsuarioLoginJSON(string eMail, string sPass, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UsuarioLoginJSON", new object[] {
                    eMail,
                    sPass}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndUsuarioLoginJSON(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void UsuarioLoginJSONAsync(string eMail, string sPass) {
        this.UsuarioLoginJSONAsync(eMail, sPass, null);
    }
    
    /// <remarks/>
    public void UsuarioLoginJSONAsync(string eMail, string sPass, object userState) {
        if ((this.UsuarioLoginJSONOperationCompleted == null)) {
            this.UsuarioLoginJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUsuarioLoginJSONOperationCompleted);
        }
        this.InvokeAsync("UsuarioLoginJSON", new object[] {
                    eMail,
                    sPass}, this.UsuarioLoginJSONOperationCompleted, userState);
    }
    
    private void OnUsuarioLoginJSONOperationCompleted(object arg) {
        if ((this.UsuarioLoginJSONCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UsuarioLoginJSONCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectJuegoXIDJuego", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public SelectJuegoXIDJuegoResult[] SelectJuegoXIDJuego(int iDJuego) {
        object[] results = this.Invoke("SelectJuegoXIDJuego", new object[] {
                    iDJuego});
        return ((SelectJuegoXIDJuegoResult[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSelectJuegoXIDJuego(int iDJuego, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SelectJuegoXIDJuego", new object[] {
                    iDJuego}, callback, asyncState);
    }
    
    /// <remarks/>
    public SelectJuegoXIDJuegoResult[] EndSelectJuegoXIDJuego(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((SelectJuegoXIDJuegoResult[])(results[0]));
    }
    
    /// <remarks/>
    public void SelectJuegoXIDJuegoAsync(int iDJuego) {
        this.SelectJuegoXIDJuegoAsync(iDJuego, null);
    }
    
    /// <remarks/>
    public void SelectJuegoXIDJuegoAsync(int iDJuego, object userState) {
        if ((this.SelectJuegoXIDJuegoOperationCompleted == null)) {
            this.SelectJuegoXIDJuegoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectJuegoXIDJuegoOperationCompleted);
        }
        this.InvokeAsync("SelectJuegoXIDJuego", new object[] {
                    iDJuego}, this.SelectJuegoXIDJuegoOperationCompleted, userState);
    }
    
    private void OnSelectJuegoXIDJuegoOperationCompleted(object arg) {
        if ((this.SelectJuegoXIDJuegoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SelectJuegoXIDJuegoCompleted(this, new SelectJuegoXIDJuegoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectLstCanicasXIDJuego", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public SelectLstCanicasXIDJuegoResult[] SelectLstCanicasXIDJuego(int iDJuego) {
        object[] results = this.Invoke("SelectLstCanicasXIDJuego", new object[] {
                    iDJuego});
        return ((SelectLstCanicasXIDJuegoResult[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSelectLstCanicasXIDJuego(int iDJuego, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SelectLstCanicasXIDJuego", new object[] {
                    iDJuego}, callback, asyncState);
    }
    
    /// <remarks/>
    public SelectLstCanicasXIDJuegoResult[] EndSelectLstCanicasXIDJuego(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((SelectLstCanicasXIDJuegoResult[])(results[0]));
    }
    
    /// <remarks/>
    public void SelectLstCanicasXIDJuegoAsync(int iDJuego) {
        this.SelectLstCanicasXIDJuegoAsync(iDJuego, null);
    }
    
    /// <remarks/>
    public void SelectLstCanicasXIDJuegoAsync(int iDJuego, object userState) {
        if ((this.SelectLstCanicasXIDJuegoOperationCompleted == null)) {
            this.SelectLstCanicasXIDJuegoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectLstCanicasXIDJuegoOperationCompleted);
        }
        this.InvokeAsync("SelectLstCanicasXIDJuego", new object[] {
                    iDJuego}, this.SelectLstCanicasXIDJuegoOperationCompleted, userState);
    }
    
    private void OnSelectLstCanicasXIDJuegoOperationCompleted(object arg) {
        if ((this.SelectLstCanicasXIDJuegoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SelectLstCanicasXIDJuegoCompleted(this, new SelectLstCanicasXIDJuegoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectLstJuegosXsAlias", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public SelectLstJuegosXsAliasResult[] SelectLstJuegosXsAlias(string sAlias) {
        object[] results = this.Invoke("SelectLstJuegosXsAlias", new object[] {
                    sAlias});
        return ((SelectLstJuegosXsAliasResult[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSelectLstJuegosXsAlias(string sAlias, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SelectLstJuegosXsAlias", new object[] {
                    sAlias}, callback, asyncState);
    }
    
    /// <remarks/>
    public SelectLstJuegosXsAliasResult[] EndSelectLstJuegosXsAlias(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((SelectLstJuegosXsAliasResult[])(results[0]));
    }
    
    /// <remarks/>
    public void SelectLstJuegosXsAliasAsync(string sAlias) {
        this.SelectLstJuegosXsAliasAsync(sAlias, null);
    }
    
    /// <remarks/>
    public void SelectLstJuegosXsAliasAsync(string sAlias, object userState) {
        if ((this.SelectLstJuegosXsAliasOperationCompleted == null)) {
            this.SelectLstJuegosXsAliasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectLstJuegosXsAliasOperationCompleted);
        }
        this.InvokeAsync("SelectLstJuegosXsAlias", new object[] {
                    sAlias}, this.SelectLstJuegosXsAliasOperationCompleted, userState);
    }
    
    private void OnSelectLstJuegosXsAliasOperationCompleted(object arg) {
        if ((this.SelectLstJuegosXsAliasCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SelectLstJuegosXsAliasCompleted(this, new SelectLstJuegosXsAliasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UsuarioLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public UsuarioLoginResult[] UsuarioLogin(string eMail, string sPass) {
        object[] results = this.Invoke("UsuarioLogin", new object[] {
                    eMail,
                    sPass});
        return ((UsuarioLoginResult[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUsuarioLogin(string eMail, string sPass, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UsuarioLogin", new object[] {
                    eMail,
                    sPass}, callback, asyncState);
    }
    
    /// <remarks/>
    public UsuarioLoginResult[] EndUsuarioLogin(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((UsuarioLoginResult[])(results[0]));
    }
    
    /// <remarks/>
    public void UsuarioLoginAsync(string eMail, string sPass) {
        this.UsuarioLoginAsync(eMail, sPass, null);
    }
    
    /// <remarks/>
    public void UsuarioLoginAsync(string eMail, string sPass, object userState) {
        if ((this.UsuarioLoginOperationCompleted == null)) {
            this.UsuarioLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUsuarioLoginOperationCompleted);
        }
        this.InvokeAsync("UsuarioLogin", new object[] {
                    eMail,
                    sPass}, this.UsuarioLoginOperationCompleted, userState);
    }
    
    private void OnUsuarioLoginOperationCompleted(object arg) {
        if ((this.UsuarioLoginCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UsuarioLoginCompleted(this, new UsuarioLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteAmigoJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void DeleteAmigoJSON(int iDUsuario, int iDUsuarioAmigo) {
        this.Invoke("DeleteAmigoJSON", new object[] {
                    iDUsuario,
                    iDUsuarioAmigo});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDeleteAmigoJSON(int iDUsuario, int iDUsuarioAmigo, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeleteAmigoJSON", new object[] {
                    iDUsuario,
                    iDUsuarioAmigo}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndDeleteAmigoJSON(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void DeleteAmigoJSONAsync(int iDUsuario, int iDUsuarioAmigo) {
        this.DeleteAmigoJSONAsync(iDUsuario, iDUsuarioAmigo, null);
    }
    
    /// <remarks/>
    public void DeleteAmigoJSONAsync(int iDUsuario, int iDUsuarioAmigo, object userState) {
        if ((this.DeleteAmigoJSONOperationCompleted == null)) {
            this.DeleteAmigoJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteAmigoJSONOperationCompleted);
        }
        this.InvokeAsync("DeleteAmigoJSON", new object[] {
                    iDUsuario,
                    iDUsuarioAmigo}, this.DeleteAmigoJSONOperationCompleted, userState);
    }
    
    private void OnDeleteAmigoJSONOperationCompleted(object arg) {
        if ((this.DeleteAmigoJSONCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DeleteAmigoJSONCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteJuegoJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void DeleteJuegoJSON(int iDJuego) {
        this.Invoke("DeleteJuegoJSON", new object[] {
                    iDJuego});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDeleteJuegoJSON(int iDJuego, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeleteJuegoJSON", new object[] {
                    iDJuego}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndDeleteJuegoJSON(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void DeleteJuegoJSONAsync(int iDJuego) {
        this.DeleteJuegoJSONAsync(iDJuego, null);
    }
    
    /// <remarks/>
    public void DeleteJuegoJSONAsync(int iDJuego, object userState) {
        if ((this.DeleteJuegoJSONOperationCompleted == null)) {
            this.DeleteJuegoJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteJuegoJSONOperationCompleted);
        }
        this.InvokeAsync("DeleteJuegoJSON", new object[] {
                    iDJuego}, this.DeleteJuegoJSONOperationCompleted, userState);
    }
    
    private void OnDeleteJuegoJSONOperationCompleted(object arg) {
        if ((this.DeleteJuegoJSONCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DeleteJuegoJSONCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteAmigo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string DeleteAmigo(int iDUsuario, int iDUsuarioAmigo) {
        object[] results = this.Invoke("DeleteAmigo", new object[] {
                    iDUsuario,
                    iDUsuarioAmigo});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDeleteAmigo(int iDUsuario, int iDUsuarioAmigo, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeleteAmigo", new object[] {
                    iDUsuario,
                    iDUsuarioAmigo}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndDeleteAmigo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void DeleteAmigoAsync(int iDUsuario, int iDUsuarioAmigo) {
        this.DeleteAmigoAsync(iDUsuario, iDUsuarioAmigo, null);
    }
    
    /// <remarks/>
    public void DeleteAmigoAsync(int iDUsuario, int iDUsuarioAmigo, object userState) {
        if ((this.DeleteAmigoOperationCompleted == null)) {
            this.DeleteAmigoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteAmigoOperationCompleted);
        }
        this.InvokeAsync("DeleteAmigo", new object[] {
                    iDUsuario,
                    iDUsuarioAmigo}, this.DeleteAmigoOperationCompleted, userState);
    }
    
    private void OnDeleteAmigoOperationCompleted(object arg) {
        if ((this.DeleteAmigoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DeleteAmigoCompleted(this, new DeleteAmigoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteJuego", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string DeleteJuego(int iDJuego) {
        object[] results = this.Invoke("DeleteJuego", new object[] {
                    iDJuego});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDeleteJuego(int iDJuego, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeleteJuego", new object[] {
                    iDJuego}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndDeleteJuego(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void DeleteJuegoAsync(int iDJuego) {
        this.DeleteJuegoAsync(iDJuego, null);
    }
    
    /// <remarks/>
    public void DeleteJuegoAsync(int iDJuego, object userState) {
        if ((this.DeleteJuegoOperationCompleted == null)) {
            this.DeleteJuegoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteJuegoOperationCompleted);
        }
        this.InvokeAsync("DeleteJuego", new object[] {
                    iDJuego}, this.DeleteJuegoOperationCompleted, userState);
    }
    
    private void OnDeleteJuegoOperationCompleted(object arg) {
        if ((this.DeleteJuegoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DeleteJuegoCompleted(this, new DeleteJuegoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class SelectLstCatalogoTamanioResult {
    
    private int iDCatalogoTamanioField;
    
    private string sDescripcionField;
    
    private bool bActivaField;
    
    /// <comentarios/>
    public int IDCatalogoTamanio {
        get {
            return this.iDCatalogoTamanioField;
        }
        set {
            this.iDCatalogoTamanioField = value;
        }
    }
    
    /// <comentarios/>
    public string sDescripcion {
        get {
            return this.sDescripcionField;
        }
        set {
            this.sDescripcionField = value;
        }
    }
    
    /// <comentarios/>
    public bool bActiva {
        get {
            return this.bActivaField;
        }
        set {
            this.bActivaField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class UsuarioLoginResult {
    
    private int iDUsuarioField;
    
    private string eMailField;
    
    private string sAliasField;
    
    /// <comentarios/>
    public int IDUsuario {
        get {
            return this.iDUsuarioField;
        }
        set {
            this.iDUsuarioField = value;
        }
    }
    
    /// <comentarios/>
    public string EMail {
        get {
            return this.eMailField;
        }
        set {
            this.eMailField = value;
        }
    }
    
    /// <comentarios/>
    public string sAlias {
        get {
            return this.sAliasField;
        }
        set {
            this.sAliasField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class SelectLstJuegosXsAliasResult {
    
    private int iDJuegoField;
    
    private int iDUsuarioField;
    
    private int iDCatalogoEscenarioField;
    
    private string sNombreField;
    
    private System.DateTime dFechaField;
    
    private bool bActivoField;
    
    /// <comentarios/>
    public int IDJuego {
        get {
            return this.iDJuegoField;
        }
        set {
            this.iDJuegoField = value;
        }
    }
    
    /// <comentarios/>
    public int IDUsuario {
        get {
            return this.iDUsuarioField;
        }
        set {
            this.iDUsuarioField = value;
        }
    }
    
    /// <comentarios/>
    public int IDCatalogoEscenario {
        get {
            return this.iDCatalogoEscenarioField;
        }
        set {
            this.iDCatalogoEscenarioField = value;
        }
    }
    
    /// <comentarios/>
    public string sNombre {
        get {
            return this.sNombreField;
        }
        set {
            this.sNombreField = value;
        }
    }
    
    /// <comentarios/>
    public System.DateTime dFecha {
        get {
            return this.dFechaField;
        }
        set {
            this.dFechaField = value;
        }
    }
    
    /// <comentarios/>
    public bool bActivo {
        get {
            return this.bActivoField;
        }
        set {
            this.bActivoField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class SelectLstCanicasXIDJuegoResult {
    
    private int iDUsuarioField;
    
    private int iDJuegoField;
    
    private int iDCatalogoCanicaField;
    
    private double fxField;
    
    private double fyField;
    
    private double fzField;
    
    /// <comentarios/>
    public int IDUsuario {
        get {
            return this.iDUsuarioField;
        }
        set {
            this.iDUsuarioField = value;
        }
    }
    
    /// <comentarios/>
    public int IDJuego {
        get {
            return this.iDJuegoField;
        }
        set {
            this.iDJuegoField = value;
        }
    }
    
    /// <comentarios/>
    public int IDCatalogoCanica {
        get {
            return this.iDCatalogoCanicaField;
        }
        set {
            this.iDCatalogoCanicaField = value;
        }
    }
    
    /// <comentarios/>
    public double fX {
        get {
            return this.fxField;
        }
        set {
            this.fxField = value;
        }
    }
    
    /// <comentarios/>
    public double fY {
        get {
            return this.fyField;
        }
        set {
            this.fyField = value;
        }
    }
    
    /// <comentarios/>
    public double fZ {
        get {
            return this.fzField;
        }
        set {
            this.fzField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class SelectJuegoXIDJuegoResult {
    
    private int iDJuegoField;
    
    private int iDUsuarioField;
    
    private int iDCatalogoEscenarioField;
    
    private string sNombreField;
    
    private System.DateTime dFechaField;
    
    private bool bActivoField;
    
    /// <comentarios/>
    public int IDJuego {
        get {
            return this.iDJuegoField;
        }
        set {
            this.iDJuegoField = value;
        }
    }
    
    /// <comentarios/>
    public int IDUsuario {
        get {
            return this.iDUsuarioField;
        }
        set {
            this.iDUsuarioField = value;
        }
    }
    
    /// <comentarios/>
    public int IDCatalogoEscenario {
        get {
            return this.iDCatalogoEscenarioField;
        }
        set {
            this.iDCatalogoEscenarioField = value;
        }
    }
    
    /// <comentarios/>
    public string sNombre {
        get {
            return this.sNombreField;
        }
        set {
            this.sNombreField = value;
        }
    }
    
    /// <comentarios/>
    public System.DateTime dFecha {
        get {
            return this.dFechaField;
        }
        set {
            this.dFechaField = value;
        }
    }
    
    /// <comentarios/>
    public bool bActivo {
        get {
            return this.bActivoField;
        }
        set {
            this.bActivoField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class InsertJuegoResult {
    
    private int iDJuegoField;
    
    private string sNombreField;
    
    private System.DateTime dFechaField;
    
    /// <comentarios/>
    public int IDJuego {
        get {
            return this.iDJuegoField;
        }
        set {
            this.iDJuegoField = value;
        }
    }
    
    /// <comentarios/>
    public string sNombre {
        get {
            return this.sNombreField;
        }
        set {
            this.sNombreField = value;
        }
    }
    
    /// <comentarios/>
    public System.DateTime dFecha {
        get {
            return this.dFechaField;
        }
        set {
            this.dFechaField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class InsertUpdateUsuariosResult {
    
    private int iDUsuarioField;
    
    private string eMailField;
    
    private string sAliasField;
    
    /// <comentarios/>
    public int IDUsuario {
        get {
            return this.iDUsuarioField;
        }
        set {
            this.iDUsuarioField = value;
        }
    }
    
    /// <comentarios/>
    public string EMail {
        get {
            return this.eMailField;
        }
        set {
            this.eMailField = value;
        }
    }
    
    /// <comentarios/>
    public string sAlias {
        get {
            return this.sAliasField;
        }
        set {
            this.sAliasField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class SelectLstCatalogoCanicaResult {
    
    private int iDCatalogoCanicaField;
    
    private int iDCatalogoTamanioField;
    
    private string sNombreField;
    
    private string sDescripciónField;
    
    private bool bActivaField;
    
    /// <comentarios/>
    public int IDCatalogoCanica {
        get {
            return this.iDCatalogoCanicaField;
        }
        set {
            this.iDCatalogoCanicaField = value;
        }
    }
    
    /// <comentarios/>
    public int IDCatalogoTamanio {
        get {
            return this.iDCatalogoTamanioField;
        }
        set {
            this.iDCatalogoTamanioField = value;
        }
    }
    
    /// <comentarios/>
    public string sNombre {
        get {
            return this.sNombreField;
        }
        set {
            this.sNombreField = value;
        }
    }
    
    /// <comentarios/>
    public string sDescripción {
        get {
            return this.sDescripciónField;
        }
        set {
            this.sDescripciónField = value;
        }
    }
    
    /// <comentarios/>
    public bool bActiva {
        get {
            return this.bActivaField;
        }
        set {
            this.bActivaField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class SelectLstCatalogoEscenariosResult {
    
    private int iDCatalogoEscenarioField;
    
    private string sNombreField;
    
    private string sDescripcionField;
    
    private bool bActivoField;
    
    /// <comentarios/>
    public int IDCatalogoEscenario {
        get {
            return this.iDCatalogoEscenarioField;
        }
        set {
            this.iDCatalogoEscenarioField = value;
        }
    }
    
    /// <comentarios/>
    public string sNombre {
        get {
            return this.sNombreField;
        }
        set {
            this.sNombreField = value;
        }
    }
    
    /// <comentarios/>
    public string sDescripcion {
        get {
            return this.sDescripcionField;
        }
        set {
            this.sDescripcionField = value;
        }
    }
    
    /// <comentarios/>
    public bool bActivo {
        get {
            return this.bActivoField;
        }
        set {
            this.bActivoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void SelectLstCatalogoTamanioJSONCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void SelectLstCatalogoEscenariosJSONCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void SelectLstCatalogoCanicaJSONCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void SelectLstCatalogoTamanioCompletedEventHandler(object sender, SelectLstCatalogoTamanioCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SelectLstCatalogoTamanioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SelectLstCatalogoTamanioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public SelectLstCatalogoTamanioResult[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((SelectLstCatalogoTamanioResult[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void SelectLstCatalogoEscenariosCompletedEventHandler(object sender, SelectLstCatalogoEscenariosCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SelectLstCatalogoEscenariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SelectLstCatalogoEscenariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public SelectLstCatalogoEscenariosResult[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((SelectLstCatalogoEscenariosResult[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void SelectLstCatalogoCanicaCompletedEventHandler(object sender, SelectLstCatalogoCanicaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SelectLstCatalogoCanicaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SelectLstCatalogoCanicaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public SelectLstCatalogoCanicaResult[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((SelectLstCatalogoCanicaResult[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void InsertUpdateUsuariosJSONCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void InsertAmigoJSONCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void InsertCanicaJSONCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void InsertJuegoJSONCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void InsertUpdateUsuariosCompletedEventHandler(object sender, InsertUpdateUsuariosCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class InsertUpdateUsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal InsertUpdateUsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public InsertUpdateUsuariosResult[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((InsertUpdateUsuariosResult[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void InsertAmigoCompletedEventHandler(object sender, InsertAmigoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class InsertAmigoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal InsertAmigoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void InsertCanicaCompletedEventHandler(object sender, InsertCanicaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class InsertCanicaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal InsertCanicaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void InsertJuegoCompletedEventHandler(object sender, InsertJuegoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class InsertJuegoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal InsertJuegoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public InsertJuegoResult[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((InsertJuegoResult[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void SelectJuegoXIDJuegoJSONCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void SelectLstCanicasXIDJuegoJSONCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void SelectLstJuegosXsAliasJSONCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void UsuarioLoginJSONCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void SelectJuegoXIDJuegoCompletedEventHandler(object sender, SelectJuegoXIDJuegoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SelectJuegoXIDJuegoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SelectJuegoXIDJuegoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public SelectJuegoXIDJuegoResult[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((SelectJuegoXIDJuegoResult[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void SelectLstCanicasXIDJuegoCompletedEventHandler(object sender, SelectLstCanicasXIDJuegoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SelectLstCanicasXIDJuegoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SelectLstCanicasXIDJuegoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public SelectLstCanicasXIDJuegoResult[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((SelectLstCanicasXIDJuegoResult[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void SelectLstJuegosXsAliasCompletedEventHandler(object sender, SelectLstJuegosXsAliasCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SelectLstJuegosXsAliasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SelectLstJuegosXsAliasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public SelectLstJuegosXsAliasResult[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((SelectLstJuegosXsAliasResult[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void UsuarioLoginCompletedEventHandler(object sender, UsuarioLoginCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UsuarioLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal UsuarioLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public UsuarioLoginResult[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((UsuarioLoginResult[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void DeleteAmigoJSONCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void DeleteJuegoJSONCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void DeleteAmigoCompletedEventHandler(object sender, DeleteAmigoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DeleteAmigoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DeleteAmigoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void DeleteJuegoCompletedEventHandler(object sender, DeleteJuegoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DeleteJuegoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DeleteJuegoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
